-- MULTIDB.USERS definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE MULTIDB.USERS;

CREATE TABLE MULTIDB.USERS (    
    username      VARCHAR2(255) NOT NULL,
    created_at    DATE NOT NULL,
    password      VARCHAR2(255) NOT NULL,
    is_active     NUMBER(1) DEFAULT 1 NOT NULL,
    department_id NUMBER(19) NULL,
    profile_id    NUMBER(19) NULL,
    CONSTRAINT pk_users PRIMARY KEY (username, created_at)
);